name: Maven CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Maven
        env:
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
        # run: mvn --batch-mode --update-snapshots verify
        run: mvn test