name: Publish CI

on:
  pull_request:
    branches:
    - master
    - integration

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Test and Publish Package
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
          RELEASE_API_PASSWORD: ${{ secrets.RELEASE_API_PASSWORD }}
        run: mvn clean deploy